import { enTranslations } from "@/content/en/index";

export const svTranslations: Record<keyof typeof enTranslations, string> = {
  'ServiceSlogan': 'Din AI-redovisare',
  'ServiceDescription': 'Countant är en AI-redovisartjänst som använder de senaste AI-modellerna för att hjälpa dig med ditt företag.',
  'ServiceName': 'Countant',
  'Select language': 'Välj språk',
  'Settings': 'Inställningar',
  'Documentation': 'Dokumentation',
  'Get Started': 'Kom igång',
  'Tutorials': 'Handledningar',
  'Changelog': 'Ändringslogg',
  'General': 'Allmänt',
  'Team': 'Team',
  'Projects': 'Projekt',
  'Toggle theme': 'Tema',
  'Light': 'Ljus',
  'Dark': 'Mörk',
  'Teams': 'Team',
  'Add team': 'Lägg till team',
  'Upgrade to Pro': 'Uppgradera till Pro',
  'Account Settings': 'Kontoinställningar',
  'Account': 'Konto',
  'Log out': 'Logga ut',
  'More': 'Mer',
  'View Project': 'Visa projekt',
  'Share Project': 'Dela projekt',
  'Delete Project': 'Ta bort projekt',
  'Dashboard': 'Dashboard',
  'Profile': 'Profil',
  'Users': 'Användare',
  'Page 1': 'Sida 1',
  'Page 2': 'Sida 2',
  'Failed to sign in with Google. Please try again.': 'Misslyckades att logga in med Google. Försök igen.',
  'Invalid email or password. Please check your credentials and try again.': 'Ogiltlig e-post eller lösenord. Kontrollera dina inloggningsuppgifter och försök igen.',
  'An error occurred during sign in. Please try again.': 'Ett fel uppstod under inloggning. Försök igen.',
  'An unexpected error occurred. Please try again.': 'Ett oväntat fel uppstod. Försök igen.',
  'Network error. Please check your connection and try again.': 'Nätverksfel. Kontrollera din anslutning och försök igen.',
  'Welcome back': 'Välkommen tillbaka',
  'Login with your Google account or email and password': 'Logga in med ditt Google-konto eller e-post och lösenord',
  'Login with Google': 'Logga in med Google',
  'Or continue with': 'Eller fortsätt med',
  'Email': 'E-post',
  'Password': 'Lösenord',
  'Forgot your password?': 'Glömt ditt lösenord?',
  'Signing in...': 'Loggar in...',
  'Login': 'Logga in',
  'Sign up': 'Registrera dig',
  'By clicking continue, you agree to our': 'Genom att klicka på fortsätt, godkänner du våra',
  'Terms of Service': 'Användarvillkor',
  'and': 'och',
  'Privacy Policy': 'Integritetspolicy',
  'Don\'t have an account?': 'Har du inget konto?',
  'Pricing': 'Pris',
  'Features': 'Funktioner',
  'Enterprise': 'Företag',
  'Blog': 'Blogg',
  'System': 'System',
  'Open menu': 'Öppna meny',
  'All rights reserved': 'Alla rättigheter reserverade',
  'Contact Information': 'Kontaktinformation',
  'Accounting Settings': 'Redovisningsinställningar',
  'Yearly': 'Helt år',
  'Monthly': 'Varje månad',
  'Failed to remove user': 'Misslyckades att ta bort användare',
  'Failed to update role': 'Misslyckades att uppdatera roll',
  'Dismiss': 'Avbryt',
  'Name': 'Namn',
  'Role': 'Roll',
  'Make Admin': 'Gör till admin',
  'Remove': 'Ta bort',
  'Invite New Member': 'Bjud in ny medlem',
  'Email Address': 'E-postadress',
  'Enter email address': 'Ange e-postadress',
  'Admin': 'Admin',
  'Sending...': 'Skickar...',
  'Cancel': 'Avbryt',
  'Saving...': 'Sparar...',
  'Save Changes': 'Spara ändringar',
  'Ask Countant': 'Fråga Countant',
  'How much tax will I have to pay this year?': 'Hur mycket skatt måste jag betala det här året?',
  'How much VAT will I have to pay this year?': 'Hur mycket moms måste jag betala det här året?',
  'What expenses can I deduct this quarter?': 'Vilka kostnader kan jag dra av det här kvartalet?',
  'When is my next VAT filing deadline?': 'När är min nästa momsredovisningsdag?',
  'Are my company ready for balancing of books?': 'Är mitt företag redo för bokslut?',
  'How will a company car affact my salary and tax?': 'Hur kommer en förmånsbil att påverka min lön och skatt?',
  'How do I optimize my company\'s tax situation?': 'Hur optimerar jag min företags skatteplats?',
  'All Invitations Processed': 'Alla inbjudan har behandlats',
  'You have responded to all pending invitations.': 'Du har svarat på alla väntande inbjudan',
  'Continue to Dashboard': 'Fortsätt till dashboard',
  'Company Invitations': 'Företagsinbjudan',
  'You have an invitation': 'Du har en inbjudan',
  'Please review and respond to each invitation below.': 'Vänligen granska och svara på varje inbjudan nedan.',
  'Invited by': 'Inbjuden av',
  'Accepting...': 'Accepterar...',
  'Accept': 'Acceptera',
  'Decline': 'Avbryt',
  'Decline Invitation': 'Avbryt inbjudan',
  'Are you sure you want to decline the invitation?': 'Är du säker på att du vill avbryta inbjudan?',
  'This action cannot be undone, and you would need to be invited again to join this company.': 'Denna åtgärd kan inte ångras, och du måste bli inbjuden igen för att kunna gå med i detta företag.',
  'My transactions': 'Mina transaktioner',
  'Invoices': 'Fakturor',
  'Offers': 'Offert',
  'Customers': 'Kunder',
  'Salaries': 'Löner',
  'Employees': 'Anställda',
  'Outlays': 'Utgifter',
  'Help': 'Hjälp',
  'Conversations': 'Konversationer',
  'Customize your settings here.': 'Anpassa dina inställningar här.',
  'New Chat': 'Nytt meddelande',
  'Rename': 'Byt namn',
  'Delete': 'Ta bort',
  'This action cannot be undone.': 'Denna åtgärd kan inte ångras.',
  'Danger Zone': 'Farlig zon',
  'cannot be undone': 'kan inte ångras',
  'Type': 'Typ',
  'delete': 'ta bort',
  'to confirm:': 'för att bekräfta:',
  'Deleting...': 'Tar bort...',
  'Something went wrong, please contact support': 'Något gick fel, kontakta supporten',
  'Users who have been invited but haven\'t accepted yet': 'Användare som har blivit inbjudna men inte accepterat',
  'Please type \'delete\' to confirm': 'Vänligen skriv \'ta bort\' för att bekräfta',
  'Type \'delete\' here': 'Skriv \'ta bort\' här',
  'Information about your company\'s annual reporting status': 'Information om ditt företags årsredovisningsstatus',
  'Company': 'Företag',
  'You must decide what to do with all companies you own.': 'Du måste bestämma vad du ska göra med alla företag du äger.',
  'Manage your account settings and logout options': 'Hantera dina kontoinställningar och utloggningsalternativ',
  'Session Management': 'Sessionshantering',
  'Sign out from your account': 'Logga ut från ditt konto',
  'Loading...': 'Laddar...',
  'Permanently delete your account and all associated data.': 'Permanenta borttagning av ditt konto och alla associerade data.',
  'You are about to permanently delete your account.': 'Du är på väg att permanent ta bort ditt konto.',
  'You own': 'Du äger',
  'Unchecked companies will require you to transfer ownership first.': 'Omarkerade företag kommer att kräva att du först överför ägarskap.',
  'Log out from all devices': 'Logga ut från alla enheter',
  'Enter a new name for this conversation': 'Ange ett nytt namn för denna konversation',
  'Enter name': 'Ange namn',
  'Are you sure you want to delete this conversation': 'Är du säker på att du vill ta bort denna konversation',
  'Deleting': 'Tar bort',
  'Manage subscription': 'Hantera prenumeration',
  'Choose the plan that\'s right for you.': 'Välj den plan som passar dig.',
  'Hobby': 'Hobby',
  'Free forever': 'Gratis för evigt',
  'The perfect starting place for your web app or personal project.': 'Den perfekta startplatsen för din webbapp eller personligt projekt.',
  '50 API calls / month': '50 API-anrop / månad',
  '60 second checks': '60 sekunders kontroller',
  'Single-user account': 'Enkel användar konto',
  '5 monitors': '5 monitorer',
  'Basic email support': 'Grundläggande e-postsupport',
  'Get started for free': 'Kom igång gratis',
  'Pro': 'Pro',
  'Everything you need to build and scale your business.': 'Allt du behöver för att bygga och skala ditt företag.',
  'Unlimited API calls': 'Oändligt API-anrop',
  '30 second checks': '30 sekunders kontroller',
  'Multi-user account': 'Multiuser konto',
  '10 monitors': '10 monitorer',
  'Priority email support': 'Prioriterad e-postsupport',
  'Subscribe to Pro': 'Prenumerera på Pro',
  'Get in touch for pricing': 'Kontakta oss för pris',
  'Critical security, performance, observability and support.': 'Kritisk säkerhet, prestanda, övervakning och support.',
  'You can DDOS our API.': 'Du kan DDOS vår API.',
  'Nano-second checks.': 'Nano-sekunders kontroller.',
  'Invite your extended family.': 'Bjud in din utökade familj.',
  'Unlimited monitors.': 'Oändligt antal monitorer.',
  'We\'ll sit on your desk.': 'Vi kommer att sitta på din skrivbord.',
  'Contact us': 'Kontakta oss',
  '20% off': '20% rabatt',
  'You have reached the limit of your current plan. Please upgrade to continue.': 'Du har nått gränsen för din nuvarande plan. Uppgradera för att fortsätta.',
  'Popular': 'Populär',
  'monthly': 'månadvis',
  'yearly': 'årvis',
  'month': 'månad',
  'billed': 'faktureras',
  'Manage Subscription': 'Hantera prenumeration',
  'Don\'t worry! You can still': 'Ingen fara! Du kan fortfarande',
  'Upgrade later when you\'re ready': 'Uppgradera senare när du är redo',
  'Try Again': 'Försök igen',
  'Billing & Subscription': 'Fakturering & Prenumeration',
  'Manage your company\'s subscription and billing': 'Hantera din företags prenumeration och fakturering',
  'Current Plan': 'Nuvarande plan',
  'Your company\'s current subscription plan': 'Din företags nuvarande prenumerationsplan',
  'Your current subscription plan': 'Din nuvarande prenumerationsplan',
  'Plan': 'Plan',
  'Next Billing Date': 'Nästa faktureringsdatum',
  'Billing History': 'Faktureringshistorik',
  'Usage & Limits': 'Användning & Gränser',
  'Track your current usage against plan limits': 'Spåra din nuvarande användning mot plangränser',
  'API Calls': 'API-anrop',
  'Storage': 'Lagring',
  'Upgrade Subscription': 'Uppgradera prenumeration',
  'Subscription Activated!': 'Prenumeration aktiverad!',
  'Subscription Canceled': 'Prenumeration avbruten',
  'Your subscription setup was canceled. No charges were made.': 'Din prenumerationsinställning har avbrutits. Inga avgifter har gjorts.',
  'Your subscription has been successfully activated': 'Din prenumeration har aktiverats',
  'Continue': 'Fortsätt',
  'Workspace Settings': 'Workspaceinställningar',
  'Customize your workspace settings here.': 'Anpassa dina workspaceinställningar här.',
  'Failed to save workspace data': 'Misslyckades att spara workspace-data',
  'General Settings': 'Allmänna inställningar',
  'Update your workspace\'s basic information.': 'Uppdatera din workspace\'s grundläggande information.',
  'Workspace Name': 'Workspace-namn',
  'Enter workspace name': 'Ange workspace-namn',
  'Workspace Type': 'Workspace-typ',
  'Select workspace type': 'Välj workspace-typ',
  'Personal': 'Personlig',
  'Description': 'Beskrivning',
  'Enter workspace description': 'Ange workspace-beskrivning',
  'Failed to save workspace information': 'Misslyckades att spara workspace-information',
  'Update your workspace\'s contact information.': 'Uppdatera din workspace\'s kontaktinformation.',
  'Failed to save accounting settings': 'Misslyckades att spara redovisningsinställningar',
  'Configure your workspace\'s accounting preferences.': 'Konfigurera din workspace\'s redovisningsinställningar.',
  'Notes': 'Anteckningar',
  'Enter accounting notes': 'Ange redovisningsanteckningar',
  'Failed to load workspace data': 'Misslyckades att ladda workspace-data',
  'Failed to send invite': 'Misslyckades att skicka inbjudan',
  'Team Management': 'Teamhantering',
  'Manage workspace members and their roles.': 'Hantera workspace-medlemmar och deras roller.',
  'Member': 'Medlem',
  'Guest': 'Gäst',
  'Send Invite': 'Skicka inbjudan',
  'Current Members': 'Nuvarande medlemmar',
  'Make Member': 'Gör till medlem',
  'Make Guest': 'Gör till gäst',
  'Pending Invites': 'Väntande inbjudan',
  'Remove User': 'Ta bort användare',
  'Are you sure you want to remove this user from the workspace? This action cannot be undone.': 'Är du säker på att du vill ta bort denna användare från workspace? Denna åtgärd kan inte ångras.',
  'Workspace name doesn\'t match': 'Workspace-namn matchar inte',
  'Failed to delete workspace': 'Misslyckades att ta bort workspace',
  'Irreversible and destructive actions.': 'Irreversibla och destruktiva åtgärder.',
  'Delete Workspace': 'Ta bort workspace',
  'Once you delete a workspace, there is no going back. Please be certain.': 'När du tar bort ett workspace, finns det inget att gå tillbaka till. Vänligen vara säker.',
  'This action cannot be undone. This will permanently delete the workspace and remove all associated data.': 'Denna åtgärd kan inte ångras. Denna åtgärd kommer att permanent ta bort workspace och ta bort alla associerade data.',
  'Please type': 'Vänligen skriv',
  'to confirm': 'för att bekräfta',
  'Workspace name': 'Workspace-namn',
  'Your workspace\'s current subscription plan': 'Din workspace\'s nuvarande prenumerationsplan',
  'Create Workspace': 'Skapa workspace',
  'Create a new workspace': 'Skapa ny workspace',
  'Create your first workspace': 'Skapa din första workspace',
  'Creating Workspace': 'Skapar workspace',
  'An error occurred while creating the workspace': 'Ett fel uppstod vid skapandet av workspace',
  'Workspace name is required': 'Workspace-namn är obligatoriskt',
  'Name must be 255 characters or less': 'Namn måste vara 255 tecken eller mindre',
  'Workspace': '',
  'Workspaces': ''} as const;

export default svTranslations;
