import { enTranslations } from "@/content/en/index";

export const svTranslations: Record<keyof typeof enTranslations, string> = {
  'ServiceSlogan': 'Din AI-redovisare',
  'ServiceDescription': 'Countant är en AI-redovisartjänst som använder de senaste AI-modellerna för att hjälpa dig med ditt företag.',
  'ServiceName': 'Countant',
  'Select language': 'Välj språk',
  'Playground': 'Spelplats',
  'History': 'Historik',
  'Starred': 'Stjärnmärkta',
  'Settings': 'Inställningar',
  'Models': 'Modeller',
  'Genesis': 'Genesis',
  'Explorer': 'Utforskare',
  'Quantum': 'Quantum',
  'Documentation': 'Dokumentation',
  'Introduction': 'Introduktion',
  'Get Started': 'Kom igång',
  'Tutorials': 'Handledningar',
  'Changelog': 'Ändringslogg',
  'General': 'Allmänt',
  'Team': 'Team',
  'Billing': 'Fakturering',
  'Limits': 'Begränsningar',
  'Design Engineering': 'Designteknik',
  'Sales & Marketing': 'Försäljning & Marknadsföring',
  'Travel': 'Resor',
  'Projects': 'Projekt',
  'Toggle theme': 'Tema',
  'Light': 'Ljus',
  'Dark': 'Mörk',
  'Teams': 'Team',
  'Add team': 'Lägg till team',
  'Upgrade to Pro': 'Uppgradera till Pro',
  'Account Settings': 'Kontoinställningar',
  'Account': 'Konto',
  'Notifications': 'Notifikationer',
  'Log out': 'Logga ut',
  'More': 'Mer',
  'View Project': 'Visa projekt',
  'Share Project': 'Dela projekt',
  'Delete Project': 'Ta bort projekt',
  'Dashboard': 'Dashboard',
  'Profile': 'Profil',
  'Users': 'Användare',
  'Page 1': 'Sida 1',
  'Page 2': 'Sida 2',
  'Navigation': 'Navigation',
  'Home': 'Hem',
  'Appearance': 'Utseende',
  'Messages & media': 'Meddelanden & media',
  'Language & region': 'Språk & region',
  'Accessibility': 'Tillgänglighet',
  'Mark as read': 'Markera som läst',
  'Audio & video': 'Ljud & video',
  'Connected accounts': 'Anslutna konton',
  'Privacy & visibility': 'Integritet & synlighet',
  'Failed to sign in with Google. Please try again.': 'Misslyckades att logga in med Google. Försök igen.',
  'Invalid email or password. Please check your credentials and try again.': 'Ogiltlig e-post eller lösenord. Kontrollera dina inloggningsuppgifter och försök igen.',
  'An error occurred during sign in. Please try again.': 'Ett fel uppstod under inloggning. Försök igen.',
  'An unexpected error occurred. Please try again.': 'Ett oväntat fel uppstod. Försök igen.',
  'Network error. Please check your connection and try again.': 'Nätverksfel. Kontrollera din anslutning och försök igen.',
  'Welcome back': 'Välkommen tillbaka',
  'Login with your Google account or email and password': 'Logga in med ditt Google-konto eller e-post och lösenord',
  'Login with Google': 'Logga in med Google',
  'Or continue with': 'Eller fortsätt med',
  'Email': 'E-post',
  'Password': 'Lösenord',
  'Forgot your password?': 'Glömt ditt lösenord?',
  'Signing in...': 'Loggar in...',
  'Login': 'Logga in',
  'Sign up': 'Registrera dig',
  'By clicking continue, you agree to our': 'Genom att klicka på fortsätt, godkänner du våra',
  'Terms of Service': 'Användarvillkor',
  'and': 'och',
  'Privacy Policy': 'Integritetspolicy',
  'Don\'t have an account?': 'Har du inget konto?',
  'Pricing': 'Pris',
  'Features': 'Funktioner',
  'Enterprise': 'Företag',
  'Blog': 'Blogg',
  'System': 'System',
  'Open menu': 'Öppna meny',
  'All rights reserved': 'Alla rättigheter reserverade',
  'Create New Company': 'Skapa nytt företag',
  'Fill in the company information to get started with your accounting': 'Fyll i företagsinformationen för att komma igång med din redovisning',
  'Creating Company': 'Skapar företag...',
  'Create Company': 'Skapa företag',
  'An error occurred while creating the company': 'Ett fel uppstod vid skapandet av företaget',
  'Basic Information': 'Grundläggande information',
  'Company Name': 'Företagsnamn',
  'Organization Number': 'Organisationsnummer',
  'VAT Registration Number': 'Momsregistreringsnummer',
  'Companies House ID': 'Bolagsverket ID',
  'Serial Number': 'Serienummer',
  'Company Type': 'Företagsform',
  'Select Company Type': 'Välj företagsform',
  'Limited Company': 'Aktiebolag',
  'General Partnership': 'Handelsbolag',
  'Limited Partnership': 'Kommanditbolag',
  'Sole Proprietorship': 'Enskild firma',
  'Housing Cooperative': 'Bostadsrättsförening',
  'Economic Association': 'Ekonomisk förening',
  'Contact Information': 'Kontaktinformation',
  'Contact Information (Optional)': 'Kontaktinformation (Valfritt)',
  'Phone': 'Telefon',
  'Contact Person': 'Kontaktperson',
  'Address': 'Adress',
  'Address Line 2': 'Adress rad 2',
  'Postal Code': 'Postnummer',
  'City': 'Ort',
  'Accounting Settings': 'Redovisningsinställningar',
  'Accounting Settings (Optional)': 'Redovisningsinställningar (Valfritt)',
  'Fiscal Year Start': 'Räkenskapsår start',
  'Fiscal Year End': 'Räkenskapsår slut',
  'VAT Reporting Period': 'Momsredovisningsperiod',
  'Select VAT Reporting Period': 'Välj momsredovisningsperiod',
  'Yearly': 'Helt år',
  'Quarterly': 'Varje kvartal',
  'Monthly': 'Varje månad',
  'Accounting Method': 'Redovisningsmetod',
  'Select Accounting Method': 'Välj redovisningsmetod',
  'Invoice Method': 'Fakturametoden',
  'Cash Method': 'Kontantmetoden',
  'Company has completed at least one annual report': 'Företaget har gjort minst ett bokslut',
  'Companies': 'Företag',
  'Company Settings': 'Företagsinställningar',
  'Unnamed Company': 'Namnlöst företag',
  'Add your first company': 'Lägg till ditt första företag',
  'Customize your company settings here.': 'Anpassa dina företagsinställningar här.',
  'Toggle menu': 'Växla meny',
  'Coming Soon': 'Kommer snart',
  'Failed to load team data': 'Misslyckades att ladda teamdata',
  'Failed to invite user': 'Misslyckades att bjuda in användare',
  'Failed to remove user': 'Misslyckades att ta bort användare',
  'Failed to transfer ownership': 'Misslyckades att överföra ägarskap',
  'Failed to update role': 'Misslyckades att uppdatera roll',
  'Loading team data...': 'Laddar teamdata...',
  'Dismiss': 'Avbryt',
  'No team members found': 'Inga teammedlemmar hittades',
  'Name': 'Namn',
  'Role': 'Roll',
  'Actions': 'Åtgärder',
  'Make Admin': 'Gör till admin',
  'Make User': 'Gör till användare',
  'Transfer Ownership': 'Överför ägarskap',
  'Remove': 'Ta bort',
  'Pending Invitations': 'Väntande inbjudan',
  'Invited By': 'Inbjuden av',
  'Date': 'Datum',
  'Invite New Member': 'Bjud in ny medlem',
  'Email Address': 'E-postadress',
  'Enter email address': 'Ange e-postadress',
  'Select Role': 'Välj roll',
  'Owner': 'Ägare',
  'Admin': 'Admin',
  'User': 'Användare',
  'Sending...': 'Skickar...',
  'Send Invitation': 'Skicka inbjudan',
  'Remove Team Member': 'Ta bort teammedlem',
  'Are you sure you want to remove': 'Är du säker på att du vill ta bort',
  'from this company? This action cannot be undone.': 'från detta företag? Denna åtgärd kan inte ångras.',
  'Cancel': 'Avbryt',
  'Are you sure you want to transfer ownership to': 'Är du säker på att du vill överföra ägarskap till',
  'Failed to load company data': 'Misslyckades att ladda företagsdata',
  'Failed to save company data': 'Misslyckades att spara företagsdata',
  'Loading company data...': 'Laddar företagsdata...',
  'Saving...': 'Sparar...',
  'Save Changes': 'Spara ändringar',
  'Ask Countant': 'Fråga Countant',
  'How much tax will I have to pay this year?': 'Hur mycket skatt måste jag betala det här året?',
  'How much VAT will I have to pay this year?': 'Hur mycket moms måste jag betala det här året?',
  'What expenses can I deduct this quarter?': 'Vilka kostnader kan jag dra av det här kvartalet?',
  'When is my next VAT filing deadline?': 'När är min nästa momsredovisningsdag?',
  'Are my company ready for balancing of books?': 'Är mitt företag redo för bokslut?',
  'How will a company car affact my salary and tax?': 'Hur kommer en förmånsbil att påverka min lön och skatt?',
  'How do I optimize my company\'s tax situation?': 'Hur optimerar jag min företags skatteplats?',
  'You will become an admin and lose owner privileges. This action cannot be undone.': 'Du kommer att bli admin och förlora ägarrättigheter. Denna åtgärd kan inte ångras.',
  'All Invitations Processed': 'Alla inbjudan har behandlats',
  'You have responded to all pending invitations.': 'Du har svarat på alla väntande inbjudan',
  'Continue to Dashboard': 'Fortsätt till dashboard',
  'Company Invitations': 'Företagsinbjudan',
  'You have an invitation': 'Du har en inbjudan',
  'Please review and respond to each invitation below.': 'Vänligen granska och svara på varje inbjudan nedan.',
  'Invited by': 'Inbjuden av',
  'Accepting...': 'Accepterar...',
  'Accept': 'Acceptera',
  'Decline': 'Avbryt',
  'Decline Invitation': 'Avbryt inbjudan',
  'Are you sure you want to decline the invitation?': 'Är du säker på att du vill avbryta inbjudan?',
  'This action cannot be undone, and you would need to be invited again to join this company.': 'Denna åtgärd kan inte ångras, och du måste bli inbjuden igen för att kunna gå med i detta företag.',
  'Create a new company': 'Skapa ett nytt företag',
  'Create your first company': 'Skapa ditt första företag',
  'My transactions': 'Mina transaktioner',
  'Invoices': 'Fakturor',
  'Offers': 'Offert',
  'Customers': 'Kunder',
  'Salaries': 'Löner',
  'Employees': 'Anställda',
  'Outlays': 'Utgifter',
  'Help': 'Hjälp',
  'Conversations': 'Konversationer',
  'Platform': 'Plattform',
  'Customize your settings here.': 'Anpassa dina inställningar här.',
  'New Chat': 'Nytt meddelande',
  'Rename': 'Byt namn',
  'Delete': 'Ta bort',
  'Team Members': 'Teammedlemmar',
  'Manage team members and their roles': 'Hantera teammedlemmar och deras roller',
  'Send an invitation to add someone to your team': 'Skicka inbjudan för att lägga till någon i ditt team',
  'from this company?': 'från detta företag?',
  'This action cannot be undone.': 'Denna åtgärd kan inte ångras.',
  'You will become an admin and lose owner privileges.': 'Du kommer att bli admin och förlora ägarrättigheter.',
  'Essential company details and registration information': 'Essentiella företagsdetaljer och registreringsinformation',
  'Enter company name': 'Ange företagsnamn',
  'Enter organization number': 'Ange organisationsnummer',
  'Failed to delete company': 'Misslyckades att ta bort företag',
  'Danger Zone': 'Farlig zon',
  'Irreversible and destructive actions for your company': 'Oåterkalleliga och destruktiva åtgärder för ditt företag',
  'Delete Company': 'Ta bort företag',
  'Permanently delete': 'Permanenta borttagning',
  'This action cannot be undone and will remove data.': 'Denna åtgärd kan inte ångras och kommer att ta bort data.',
  'This will delete:': 'Detta kommer att ta bort:',
  'All data associated with the company': 'All data associerad med företaget',
  'You are about to permanently delete': 'Du är på väg att permanent ta bort',
  'This action': 'Denna åtgärd',
  'cannot be undone': 'kan inte ångras',
  'Type': 'Typ',
  'delete': 'ta bort',
  'to confirm:': 'för att bekräfta:',
  'Deleting...': 'Tar bort...',
  'Something went wrong, please contact support': 'Något gick fel, kontakta supporten',
  'Address Information': 'Adressinformation',
  'Company physical address and location details': 'Fysisk adress och platsinformation för företaget',
  'Apartment, suite, etc. (optional)': 'Bostad, lägenhet, etc. (valfritt)',
  'Phone, email, and contact person details': 'Telefon, e-post och kontaktperson',
  'Failed to update company': 'Misslyckades att uppdatera företag',
  'VAT & Tax Settings': 'Moms & Skattinställningar',
  'Configure VAT reporting and tax-related settings': 'Konfigurera momsredovisning och skatterelaterade inställningar',
  'Choose the accounting method for your company': 'Välj redovisningsmetod för ditt företag',
  'Annual Report Status': 'Årsredovisningsstatus',
  'No team members will be able to access the company or recover it': 'Inga teammedlemmar kommer att kunna komma åt företaget eller återställa det',
  'The company and all its data will be permanently deleted': 'Företaget och all dess data kommer att permanent borttagas',
  'and will permanently remove all data associated with this company': 'och kommer att permanent ta bort all data associerad med detta företag',
  'Check this if your company has already filed at least one annual report': 'Kryssa i detta om ditt företag har gjort minst ett bokslut',
  'Users who have been invited but haven\'t accepted yet': 'Användare som har blivit inbjudna men inte accepterat',
  'Please type \'delete\' to confirm': 'Vänligen skriv \'ta bort\' för att bekräfta',
  'Type \'delete\' here': 'Skriv \'ta bort\' här',
  'Information about your company\'s annual reporting status': 'Information om ditt företags årsredovisningsstatus',
  'Leave': 'Lämna',
  'Company': 'Företag',
  'As the company owner, you cannot leave the company directly.': 'Som företagsägare kan du inte lämna företaget direkt.',
  'To leave this company, you need to transfer ownership to another team member first.': 'För att lämna detta företag måste du först överföra ägarskap till en annan teammedlem.'} as const;

export default svTranslations;
