import { enTranslations } from "@/content/en/index";

export const svTranslations: Record<keyof typeof enTranslations, string> = {
  'ServiceSlogan': 'Din AI-redovisare',
  'ServiceDescription': 'Countant är en AI-redovisartjänst som använder de senaste AI-modellerna för att hjälpa dig med ditt företag.',
  'ServiceName': 'Countant',
  'Select language': 'Välj språk',
  'Settings': 'Inställningar',
  'Documentation': 'Dokumentation',
  'Get Started': 'Kom igång',
  'Tutorials': 'Handledningar',
  'Changelog': 'Ändringslogg',
  'General': 'Allmänt',
  'Team': 'Team',
  'Projects': 'Projekt',
  'Toggle theme': 'Tema',
  'Light': 'Ljus',
  'Dark': 'Mörk',
  'Teams': 'Team',
  'Add team': 'Lägg till team',
  'Upgrade to Pro': 'Uppgradera till Pro',
  'Account Settings': 'Kontoinställningar',
  'Account': 'Konto',
  'Log out': 'Logga ut',
  'More': 'Mer',
  'View Project': 'Visa projekt',
  'Share Project': 'Dela projekt',
  'Delete Project': 'Ta bort projekt',
  'Dashboard': 'Dashboard',
  'Profile': 'Profil',
  'Users': 'Användare',
  'Page 1': 'Sida 1',
  'Page 2': 'Sida 2',
  'Failed to sign in with Google. Please try again.': 'Misslyckades att logga in med Google. Försök igen.',
  'Invalid email or password. Please check your credentials and try again.': 'Ogiltlig e-post eller lösenord. Kontrollera dina inloggningsuppgifter och försök igen.',
  'An error occurred during sign in. Please try again.': 'Ett fel uppstod under inloggning. Försök igen.',
  'An unexpected error occurred. Please try again.': 'Ett oväntat fel uppstod. Försök igen.',
  'Network error. Please check your connection and try again.': 'Nätverksfel. Kontrollera din anslutning och försök igen.',
  'Welcome back': 'Välkommen tillbaka',
  'Login with your Google account or email and password': 'Logga in med ditt Google-konto eller e-post och lösenord',
  'Login with Google': 'Logga in med Google',
  'Or continue with': 'Eller fortsätt med',
  'Email': 'E-post',
  'Password': 'Lösenord',
  'Forgot your password?': 'Glömt ditt lösenord?',
  'Signing in...': 'Loggar in...',
  'Login': 'Logga in',
  'Sign up': 'Registrera dig',
  'By clicking continue, you agree to our': 'Genom att klicka på fortsätt, godkänner du våra',
  'Terms of Service': 'Användarvillkor',
  'and': 'och',
  'Privacy Policy': 'Integritetspolicy',
  'Don\'t have an account?': 'Har du inget konto?',
  'Pricing': 'Pris',
  'Features': 'Funktioner',
  'Enterprise': 'Företag',
  'Blog': 'Blogg',
  'System': 'System',
  'Open menu': 'Öppna meny',
  'All rights reserved': 'Alla rättigheter reserverade',
  'Fill in the company information to get started with your accounting': 'Fyll i företagsinformationen för att komma igång med din redovisning',
  'Creating Company': 'Skapar företag...',
  'Create Company': 'Skapa företag',
  'An error occurred while creating the company': 'Ett fel uppstod vid skapandet av företaget',
  'Basic Information': 'Grundläggande information',
  'Company Name': 'Företagsnamn',
  'Organization Number': 'Organisationsnummer',
  'VAT Registration Number': 'Momsregistreringsnummer',
  'Company Type': 'Företagsform',
  'Select Company Type': 'Välj företagsform',
  'Limited Company': 'Aktiebolag',
  'General Partnership': 'Handelsbolag',
  'Limited Partnership': 'Kommanditbolag',
  'Sole Proprietorship': 'Enskild firma',
  'Housing Cooperative': 'Bostadsrättsförening',
  'Economic Association': 'Ekonomisk förening',
  'Contact Information': 'Kontaktinformation',
  'Contact Information (Optional)': 'Kontaktinformation (Valfritt)',
  'Phone': 'Telefon',
  'Contact Person': 'Kontaktperson',
  'Address': 'Adress',
  'Address Line 2': 'Adress rad 2',
  'Postal Code': 'Postnummer',
  'City': 'Ort',
  'Accounting Settings': 'Redovisningsinställningar',
  'Accounting Settings (Optional)': 'Redovisningsinställningar (Valfritt)',
  'Fiscal Year Start': 'Räkenskapsår start',
  'Fiscal Year End': 'Räkenskapsår slut',
  'VAT Reporting Period': 'Momsredovisningsperiod',
  'Select VAT Reporting Period': 'Välj momsredovisningsperiod',
  'Yearly': 'Helt år',
  'Quarterly': 'Varje kvartal',
  'Monthly': 'Varje månad',
  'Accounting Method': 'Redovisningsmetod',
  'Select Accounting Method': 'Välj redovisningsmetod',
  'Invoice Method': 'Fakturametoden',
  'Cash Method': 'Kontantmetoden',
  'Company has completed at least one annual report': 'Företaget har gjort minst ett bokslut',
  'Companies': 'Företag',
  'Company Settings': 'Företagsinställningar',
  'Unnamed Company': 'Namnlöst företag',
  'Customize your company settings here.': 'Anpassa dina företagsinställningar här.',
  'Failed to load team data': 'Misslyckades att ladda teamdata',
  'Failed to invite user': 'Misslyckades att bjuda in användare',
  'Failed to remove user': 'Misslyckades att ta bort användare',
  'Failed to transfer ownership': 'Misslyckades att överföra ägarskap',
  'Failed to update role': 'Misslyckades att uppdatera roll',
  'Loading team data...': 'Laddar teamdata...',
  'Dismiss': 'Avbryt',
  'No team members found': 'Inga teammedlemmar hittades',
  'Name': 'Namn',
  'Role': 'Roll',
  'Make Admin': 'Gör till admin',
  'Make User': 'Gör till användare',
  'Transfer Ownership': 'Överför ägarskap',
  'Remove': 'Ta bort',
  'Pending Invitations': 'Väntande inbjudan',
  'Invite New Member': 'Bjud in ny medlem',
  'Email Address': 'E-postadress',
  'Enter email address': 'Ange e-postadress',
  'Select Role': 'Välj roll',
  'Admin': 'Admin',
  'User': 'Användare',
  'Sending...': 'Skickar...',
  'Send Invitation': 'Skicka inbjudan',
  'Remove Team Member': 'Ta bort teammedlem',
  'Are you sure you want to remove': 'Är du säker på att du vill ta bort',
  'Cancel': 'Avbryt',
  'Are you sure you want to transfer ownership to': 'Är du säker på att du vill överföra ägarskap till',
  'Failed to save company data': 'Misslyckades att spara företagsdata',
  'Saving...': 'Sparar...',
  'Save Changes': 'Spara ändringar',
  'Ask Countant': 'Fråga Countant',
  'How much tax will I have to pay this year?': 'Hur mycket skatt måste jag betala det här året?',
  'How much VAT will I have to pay this year?': 'Hur mycket moms måste jag betala det här året?',
  'What expenses can I deduct this quarter?': 'Vilka kostnader kan jag dra av det här kvartalet?',
  'When is my next VAT filing deadline?': 'När är min nästa momsredovisningsdag?',
  'Are my company ready for balancing of books?': 'Är mitt företag redo för bokslut?',
  'How will a company car affact my salary and tax?': 'Hur kommer en förmånsbil att påverka min lön och skatt?',
  'How do I optimize my company\'s tax situation?': 'Hur optimerar jag min företags skatteplats?',
  'All Invitations Processed': 'Alla inbjudan har behandlats',
  'You have responded to all pending invitations.': 'Du har svarat på alla väntande inbjudan',
  'Continue to Dashboard': 'Fortsätt till dashboard',
  'Company Invitations': 'Företagsinbjudan',
  'You have an invitation': 'Du har en inbjudan',
  'Please review and respond to each invitation below.': 'Vänligen granska och svara på varje inbjudan nedan.',
  'Invited by': 'Inbjuden av',
  'Accepting...': 'Accepterar...',
  'Accept': 'Acceptera',
  'Decline': 'Avbryt',
  'Decline Invitation': 'Avbryt inbjudan',
  'Are you sure you want to decline the invitation?': 'Är du säker på att du vill avbryta inbjudan?',
  'This action cannot be undone, and you would need to be invited again to join this company.': 'Denna åtgärd kan inte ångras, och du måste bli inbjuden igen för att kunna gå med i detta företag.',
  'Create a new company': 'Skapa ett nytt företag',
  'Create your first company': 'Skapa ditt första företag',
  'My transactions': 'Mina transaktioner',
  'Invoices': 'Fakturor',
  'Offers': 'Offert',
  'Customers': 'Kunder',
  'Salaries': 'Löner',
  'Employees': 'Anställda',
  'Outlays': 'Utgifter',
  'Help': 'Hjälp',
  'Conversations': 'Konversationer',
  'Platform': 'Plattform',
  'Customize your settings here.': 'Anpassa dina inställningar här.',
  'New Chat': 'Nytt meddelande',
  'Rename': 'Byt namn',
  'Delete': 'Ta bort',
  'Team Members': 'Teammedlemmar',
  'Manage team members and their roles': 'Hantera teammedlemmar och deras roller',
  'Send an invitation to add someone to your team': 'Skicka inbjudan för att lägga till någon i ditt team',
  'from this company?': 'från detta företag?',
  'This action cannot be undone.': 'Denna åtgärd kan inte ångras.',
  'You will become an admin and lose owner privileges.': 'Du kommer att bli admin och förlora ägarrättigheter.',
  'Essential company details and registration information': 'Essentiella företagsdetaljer och registreringsinformation',
  'Enter company name': 'Ange företagsnamn',
  'Enter organization number': 'Ange organisationsnummer',
  'Failed to delete company': 'Misslyckades att ta bort företag',
  'Danger Zone': 'Farlig zon',
  'Irreversible and destructive actions for your company': 'Oåterkalleliga och destruktiva åtgärder för ditt företag',
  'Delete Company': 'Ta bort företag',
  'Permanently delete': 'Permanenta borttagning',
  'This action cannot be undone and will remove data.': 'Denna åtgärd kan inte ångras och kommer att ta bort data.',
  'This will delete:': 'Detta kommer att ta bort:',
  'All data associated with the company': 'All data associerad med företaget',
  'You are about to permanently delete': 'Du är på väg att permanent ta bort',
  'This action': 'Denna åtgärd',
  'cannot be undone': 'kan inte ångras',
  'Type': 'Typ',
  'delete': 'ta bort',
  'to confirm:': 'för att bekräfta:',
  'Deleting...': 'Tar bort...',
  'Something went wrong, please contact support': 'Något gick fel, kontakta supporten',
  'Address Information': 'Adressinformation',
  'Company physical address and location details': 'Fysisk adress och platsinformation för företaget',
  'Apartment, suite, etc. (optional)': 'Bostad, lägenhet, etc. (valfritt)',
  'Phone, email, and contact person details': 'Telefon, e-post och kontaktperson',
  'Failed to update company': 'Misslyckades att uppdatera företag',
  'VAT & Tax Settings': 'Moms & Skattinställningar',
  'Configure VAT reporting and tax-related settings': 'Konfigurera momsredovisning och skatterelaterade inställningar',
  'Choose the accounting method for your company': 'Välj redovisningsmetod för ditt företag',
  'Annual Report Status': 'Årsredovisningsstatus',
  'No team members will be able to access the company or recover it': 'Inga teammedlemmar kommer att kunna komma åt företaget eller återställa det',
  'The company and all its data will be permanently deleted': 'Företaget och all dess data kommer att permanent borttagas',
  'and will permanently remove all data associated with this company': 'och kommer att permanent ta bort all data associerad med detta företag',
  'Check this if your company has already filed at least one annual report': 'Kryssa i detta om ditt företag har gjort minst ett bokslut',
  'Users who have been invited but haven\'t accepted yet': 'Användare som har blivit inbjudna men inte accepterat',
  'Please type \'delete\' to confirm': 'Vänligen skriv \'ta bort\' för att bekräfta',
  'Type \'delete\' here': 'Skriv \'ta bort\' här',
  'Information about your company\'s annual reporting status': 'Information om ditt företags årsredovisningsstatus',
  'Leave': 'Lämna',
  'Company': 'Företag',
  'As the company owner, you cannot leave the company directly.': 'Som företagsägare kan du inte lämna företaget direkt.',
  'To leave this company, you need to transfer ownership to another team member first.': 'För att lämna detta företag måste du först överföra ägarskap till en annan teammedlem.',
  'You must decide what to do with all companies you own.': 'Du måste bestämma vad du ska göra med alla företag du äger.',
  'Manage your account settings and logout options': 'Hantera dina kontoinställningar och utloggningsalternativ',
  'Session Management': 'Sessionshantering',
  'Sign out from your account': 'Logga ut från ditt konto',
  'Loading...': 'Laddar...',
  'Permanently delete your account and all associated data.': 'Permanenta borttagning av ditt konto och alla associerade data.',
  'You are about to permanently delete your account.': 'Du är på väg att permanent ta bort ditt konto.',
  'You own': 'Du äger',
  'Unchecked companies will require you to transfer ownership first.': 'Omarkerade företag kommer att kräva att du först överför ägarskap.',
  'Remove yourself from': 'Ta bort dig från',
  'Log out from all devices': 'Logga ut från alla enheter',
  'Enter a new name for this conversation': 'Ange ett nytt namn för denna konversation',
  'Enter name': 'Ange namn',
  'Are you sure you want to delete this conversation': 'Är du säker på att du vill ta bort denna konversation',
  'Deleting': 'Tar bort',
  'Manage subscription': 'Hantera prenumeration',
  'Choose the plan that\'s right for you.': 'Välj den plan som passar dig.',
  'Hobby': 'Hobby',
  'Free forever': 'Gratis för evigt',
  'The perfect starting place for your web app or personal project.': 'Den perfekta startplatsen för din webbapp eller personligt projekt.',
  '50 API calls / month': '50 API-anrop / månad',
  '60 second checks': '60 sekunders kontroller',
  'Single-user account': 'Enkel användar konto',
  '5 monitors': '5 monitorer',
  'Basic email support': 'Grundläggande e-postsupport',
  'Get started for free': 'Kom igång gratis',
  'Pro': 'Pro',
  'Everything you need to build and scale your business.': 'Allt du behöver för att bygga och skala ditt företag.',
  'Unlimited API calls': 'Oändligt API-anrop',
  '30 second checks': '30 sekunders kontroller',
  'Multi-user account': 'Multiuser konto',
  '10 monitors': '10 monitorer',
  'Priority email support': 'Prioriterad e-postsupport',
  'Subscribe to Pro': 'Prenumerera på Pro',
  'Get in touch for pricing': 'Kontakta oss för pris',
  'Critical security, performance, observability and support.': 'Kritisk säkerhet, prestanda, övervakning och support.',
  'You can DDOS our API.': 'Du kan DDOS vår API.',
  'Nano-second checks.': 'Nano-sekunders kontroller.',
  'Invite your extended family.': 'Bjud in din utökade familj.',
  'Unlimited monitors.': 'Oändligt antal monitorer.',
  'We\'ll sit on your desk.': 'Vi kommer att sitta på din skrivbord.',
  'Contact us': 'Kontakta oss',
  '20% off': '20% rabatt',
  'You have reached the limit of your current plan. Please upgrade to continue.': 'Du har nått gränsen för din nuvarande plan. Uppgradera för att fortsätta.',
  'Popular': 'Populär',
  'monthly': 'månadvis',
  'yearly': 'årvis',
  'month': 'månad',
  'billed': 'faktureras',
  'Manage Subscription': 'Hantera prenumeration',
  'Don\'t worry! You can still': 'Ingen fara! Du kan fortfarande',
  'Upgrade later when you\'re ready': 'Uppgradera senare när du är redo',
  'Try Again': 'Försök igen',
  'Billing & Subscription': 'Fakturering & Prenumeration',
  'Manage your company\'s subscription and billing': 'Hantera din företags prenumeration och fakturering',
  'Current Plan': 'Nuvarande plan',
  'Your company\'s current subscription plan': 'Din företags nuvarande prenumerationsplan',
  'Your current subscription plan': 'Din nuvarande prenumerationsplan',
  'Plan': 'Plan',
  'Next Billing Date': 'Nästa faktureringsdatum',
  'Billing History': 'Faktureringshistorik',
  'Usage & Limits': 'Användning & Gränser',
  'Track your current usage against plan limits': 'Spåra din nuvarande användning mot plangränser',
  'API Calls': 'API-anrop',
  'Storage': 'Lagring',
  'Upgrade Subscription': 'Uppgradera prenumeration',
  'Processing Your Subscription': '',
  'Please wait while we set up your subscription...': '',
  'Subscription Error': '',
  'There was an issue setting up your subscription': '',
  'Subscription Activated!': '',
  'Subscription Canceled': '',
  'Your subscription setup was canceled. No charges were made.': '',
  'Your subscription has been successfully activated': '',
  'Continue': ''} as const;

export default svTranslations;
