export const enTranslations = {
  'ServiceName': 'Countant',
  'ServiceSlogan': 'Your AI Accountant',
  'ServiceDescription':
    'Countant is an AI accountant service that uses the latest AI models to help you with your business.',
  'Select language': 'Select language',
  'Playground': 'Playground',
  'History': 'History',
  'Starred': 'Starred',
  'Settings': 'Settings',
  'Models': 'Models',
  'Genesis': 'Genesis',
  'Explorer': 'Explorer',
  'Quantum': 'Quantum',
  'Documentation': 'Documentation',
  'Introduction': 'Introduction',
  'Get Started': 'Get Started',
  'Tutorials': 'Tutorials',
  'Changelog': 'Changelog',
  'General': 'General',
  'Team': 'Team',
  'Billing': 'Billing',
  'Limits': 'Limits',
  'Design Engineering': 'Design Engineering',
  'Sales & Marketing': 'Sales & Marketing',
  'Travel': 'Travel',
  'Projects': 'Projects',
  'Toggle theme': 'Toggle theme',
  'Light': 'Light',
  'Dark': 'Dark',
  'Teams': 'Teams',
  'Add team': 'Add team',
  'Upgrade to Pro': 'Upgrade to Pro',
  'Account': 'Account',
  'Notifications': 'Notifications',
  'Log out': 'Log out',
  'More': 'More',
  'View Project': 'View Project',
  'Share Project': 'Share Project',
  'Delete Project': 'Delete Project',
  'Dashboard': 'Dashboard',
  'Profile': 'Profile',
  'Users': 'Users',
  'Page 1': 'Page 1',
  'Page 2': 'Page 2',
  'Navigation': 'Navigation',
  'Home': 'Home',
  'Appearance': 'Appearance',
  'Messages & media': 'Messages & media',
  'Language & region': 'Language & region',
  'Accessibility': 'Accessibility',
  'Mark as read': 'Mark as read',
  'Audio & video': 'Audio & video',
  'Connected accounts': 'Connected accounts',
  'Privacy & visibility': 'Privacy & visibility',
  'Failed to sign in with Google. Please try again.': 'Failed to sign in with Google. Please try again.',
  'Invalid email or password. Please check your credentials and try again.': 'Invalid email or password. Please check your credentials and try again.',
  'An error occurred during sign in. Please try again.': 'An error occurred during sign in. Please try again.',
  'An unexpected error occurred. Please try again.': 'An unexpected error occurred. Please try again.',
  'Network error. Please check your connection and try again.': 'Network error. Please check your connection and try again.',
  'Welcome back': 'Welcome back',
  'Login with your Google account or email and password': 'Login with your Google account or email and password',
  'Login with Google': 'Login with Google',
  'Or continue with': 'Or continue with',
  'Email': 'Email',
  'Password': 'Password',
  'Forgot your password?': 'Forgot your password?',
  'Signing in...': 'Signing in...',
  'Login': 'Login',
  'Sign up': 'Sign up',
  'By clicking continue, you agree to our': 'By clicking continue, you agree to our',
  'Terms of Service': 'Terms of Service',
  'and': 'and',
  'Privacy Policy': 'Privacy Policy',
  'Don\'t have an account?': 'Don\'t have an account?',
  'Pricing': 'Pricing',
  'Features': 'Features',
  'Enterprise': 'Enterprise',
  'Blog': 'Blog',
  'System': 'System',
  'Open menu': 'Open menu',
  'All rights reserved': 'All rights reserved',
  'Create New Company': 'Create New Company',
  'Fill in the company information to get started with your accounting': 'Fill in the company information to get started with your accounting',
  'Creating Company': 'Creating Company...',
  'Create Company': 'Create Company',
  'An error occurred while creating the company': 'An error occurred while creating the company',
  'Basic Information': 'Basic Information',
  'Company Name': 'Company Name',
  'Organization Number': 'Organization Number',
  'VAT Registration Number': 'VAT Registration Number',
  'Companies House ID': 'Companies House ID',
  'Serial Number': 'Serial Number',
  'Company Type': 'Company Type',
  'Select Company Type': 'Select Company Type',
  'Limited Company': 'Limited Company',
  'General Partnership': 'General Partnership',
  'Limited Partnership': 'Limited Partnership',
  'Sole Proprietorship': 'Sole Proprietorship',
  'Housing Cooperative': 'Housing Cooperative',
  'Economic Association': 'Economic Association',
  'Contact Information': 'Contact Information',
  'Contact Information (Optional)': 'Contact Information (Optional)',
  'Phone': 'Phone',
  'Contact Person': 'Contact Person',
  'Address': 'Address',
  'Address Line 2': 'Address Line 2',
  'Postal Code': 'Postal Code',
  'City': 'City',
  'Accounting Settings': 'Accounting Settings',
  'Accounting Settings (Optional)': 'Accounting Settings (Optional)',
  'Fiscal Year Start': 'Fiscal Year Start',
  'Fiscal Year End': 'Fiscal Year End',
  'VAT Reporting Period': 'VAT Reporting Period',
  'Select VAT Reporting Period': 'Select VAT Reporting Period',
  'Yearly': 'Yearly',
  'Quarterly': 'Quarterly',
  'Monthly': 'Monthly',
  'Accounting Method': 'Accounting Method',
  'Select Accounting Method': 'Select Accounting Method',
  'Invoice Method': 'Invoice Method',
  'Cash Method': 'Cash Method',
  'Company has completed at least one annual report': 'Company has completed at least one annual report',
  'Companies': 'Companies',
  'Company Settings': 'Company Settings',
  'Unnamed Company': 'Unnamed Company',
  'Add your first company': 'Add your first company',
  'Customize your company settings here.': 'Customize your company settings here.',
  'Toggle menu': 'Toggle menu',
  'Coming Soon': 'Coming Soon',
  'Failed to load team data': 'Failed to load team data',
  'Failed to invite user': 'Failed to invite user',
  'Failed to remove user': 'Failed to remove user',
  'Failed to transfer ownership': 'Failed to transfer ownership',
  'Failed to update role': 'Failed to update role',
  'Loading team data...': 'Loading team data...',
  'Dismiss': 'Dismiss',
  'No team members found': 'No team members found',
  'Name': 'Name',
  'Role': 'Role',
  'Actions': 'Actions',
  'Make Admin': 'Make Admin',
  'Make User': 'Make User',
  'Transfer Ownership': 'Transfer Ownership',
  'Remove': 'Remove',
  'Pending Invitations': 'Pending Invitations',
  'Invited By': 'Invited By',
  'Date': 'Date',
  'Invite New Member': 'Invite New Member',
  'Email Address': 'Email Address',
  'Enter email address': 'Enter email address',
  'Select Role': 'Select Role',
  'Owner': 'Owner',
  'Admin': 'Admin',
  'User': 'User',
  'Sending...': 'Sending...',
  'Send Invitation': 'Send Invitation',
  'Remove Team Member': 'Remove Team Member',
  'Are you sure you want to remove': 'Are you sure you want to remove',
  'from this company? This action cannot be undone.': 'from this company? This action cannot be undone.',
  'Cancel': 'Cancel',
  'Are you sure you want to transfer ownership to': 'Are you sure you want to transfer ownership to',
  'Failed to load company data': 'Failed to load company data',
  'Failed to save company data': 'Failed to save company data',
  'Loading company data...': 'Loading company data...',
  'Saving...': 'Saving...',
  'Save Changes': 'Save Changes',
  'Ask Countant': 'Ask Countant',
  'How much tax will I have to pay this year?': 'How much tax will I have to pay this year?',
  'How much VAT will I have to pay this year?': 'How much VAT will I have to pay this year?',
  'What expenses can I deduct this quarter?': 'What expenses can I deduct this quarter?',
  'When is my next VAT filing deadline?': 'When is my next VAT filing deadline?',
  'Are my company ready for balancing of books?': 'Are my company ready for balancing of books?',
  'How will a company car affact my salary and tax?': 'How will a company car affact my salary and tax?',
  'How do I optimize my company\'s tax situation?': 'How do I optimize my company\'s tax situation?',
  'You will become an admin and lose owner privileges. This action cannot be undone.': 'You will become an admin and lose owner privileges. This action cannot be undone.',
  'All Invitations Processed': 'All Invitations Processed',
  'You have responded to all pending invitations.': 'You have responded to all pending invitations.',
  'Continue to Dashboard': 'Continue to Dashboard',
  'Company Invitations': 'Company Invitations',
  'You have an invitation': 'You have an invitation',
  'Please review and respond to each invitation below.': 'Please review and respond to each invitation below.',
  'Invited by': 'Invited by',
  'Accepting...': 'Accepting...',
  'Accept': 'Accept',
  'Decline': 'Decline',
  'Decline Invitation': 'Decline Invitation',
  'Are you sure you want to decline the invitation?': 'Are you sure you want to decline the invitation?',
  'This action cannot be undone, and you would need to be invited again to join this company.': 'This action cannot be undone, and you would need to be invited again to join this company.',
  'Create a new company': 'Create a new company',
  'Create your first company': 'Create your first company'} as const;

export default enTranslations;
