export const enTranslations = {
  'ServiceName': 'Countent',
  'ServiceSlogan': 'AI Content Creation',
  'ServiceDescription':
    'Countent is an AI content creation service that uses the latest AI models to create content for your business.',
  'Select language': 'Select language',
  'Playground': 'Playground',
  'History': 'History',
  'Starred': 'Starred',
  'Settings': 'Settings',
  'Models': 'Models',
  'Genesis': 'Genesis',
  'Explorer': 'Explorer',
  'Quantum': 'Quantum',
  'Documentation': 'Documentation',
  'Introduction': 'Introduction',
  'Get Started': 'Get Started',
  'Tutorials': 'Tutorials',
  'Changelog': 'Changelog',
  'General': 'General',
  'Team': 'Team',
  'Billing': 'Billing',
  'Limits': 'Limits',
  'Design Engineering': 'Design Engineering',
  'Sales & Marketing': 'Sales & Marketing',
  'Travel': 'Travel',
  'Projects': 'Projects',
  'Toggle theme': 'Toggle theme',
  'Light': 'Light',
  'Dark': 'Dark',
  'Teams': 'Teams',
  'Add team': 'Add team',
  'Upgrade to Pro': 'Upgrade to Pro',
  'Account': 'Account',
  'Notifications': 'Notifications',
  'Log out': 'Log out',
  'More': 'More',
  'View Project': 'View Project',
  'Share Project': 'Share Project',
  'Delete Project': 'Delete Project',
  'Dashboard': 'Dashboard',
  'Profile': 'Profile',
  'Users': 'Users',
  'Page 1': 'Page 1',
  'Page 2': 'Page 2',
  'Navigation': 'Navigation',
  'Home': 'Home',
  'Appearance': 'Appearance',
  'Messages & media': 'Messages & media',
  'Language & region': 'Language & region',
  'Accessibility': 'Accessibility',
  'Mark as read': 'Mark as read',
  'Audio & video': 'Audio & video',
  'Connected accounts': 'Connected accounts',
  'Privacy & visibility': 'Privacy & visibility',
  'Failed to sign in with Google. Please try again.': 'Failed to sign in with Google. Please try again.',
  'Invalid email or password. Please check your credentials and try again.': 'Invalid email or password. Please check your credentials and try again.',
  'An error occurred during sign in. Please try again.': 'An error occurred during sign in. Please try again.',
  'An unexpected error occurred. Please try again.': 'An unexpected error occurred. Please try again.',
  'Network error. Please check your connection and try again.': 'Network error. Please check your connection and try again.',
  'Welcome back': 'Welcome back',
  'Login with your Google account or email and password': 'Login with your Google account or email and password',
  'Login with Google': 'Login with Google',
  'Or continue with': 'Or continue with',
  'Email': 'Email',
  'Password': 'Password',
  'Forgot your password?': 'Forgot your password?',
  'Signing in...': 'Signing in...',
  'Login': 'Login',
  'Sign up': 'Sign up',
  'By clicking continue, you agree to our': 'By clicking continue, you agree to our',
  'Terms of Service': 'Terms of Service',
  'and': 'and',
  'Privacy Policy': 'Privacy Policy',
  'Don\'t have an account?': 'Don\'t have an account?',
  'Pricing': 'Pricing',
  'Features': 'Features',
  'Enterprise': 'Enterprise',
  'Blog': 'Blog',
  'System': 'System',
  'Open menu': 'Open menu',
  'All rights reserved': 'All rights reserved'} as const;

export default enTranslations;
