export const enTranslations = {
  'Ask Countant': 'Ask Countant',
  'How much tax will I have to pay this year?': 'How much tax will I have to pay this year?',
  'How much VAT will I have to pay this year?': 'How much VAT will I have to pay this year?',
  'How do I optimize my company\'s tax situation?': 'How do I optimize my company\'s tax situation?',
  'What expenses can I deduct this quarter?': 'What expenses can I deduct this quarter?',
  'When is my next VAT filing deadline?': 'When is my next VAT filing deadline?',
  'Are my company ready for balancing of books?': 'Are my company ready for balancing of books?',
  'ServiceSlogan': 'ServiceSlogan',
  'ServiceDescription': 'ServiceDescription',
  'General': 'General',
  'Account': 'Account',
  'Settings': 'Settings',
  'Customize your settings here.': 'Customize your settings here.',
  'Teams': 'Teams',
  'Add team': 'Add team',
  'My transactions': 'My transactions',
  'Invoices': 'Invoices',
  'Offers': 'Offers',
  'Customers': 'Customers',
  'Salaries': 'Salaries',
  'Employees': 'Employees',
  'Outlays': 'Outlays',
  'Company Settings': 'Company Settings',
  'Upgrade to Pro': 'Upgrade to Pro',
  'Account Settings': 'Account Settings',
  'Help': 'Help',
  'Log out': 'Log out',
  'Projects': 'Projects',
  'More': 'More',
  'View Project': 'View Project',
  'Share Project': 'Share Project',
  'Delete Project': 'Delete Project',
  'Platform': 'Platform',
  'Conversations': 'Conversations',
  'New Chat': 'New Chat',
  'Rename': 'Rename',
  'Delete': 'Delete',
  'Create Company': 'Create Company',
  'Companies': 'Companies',
  'Dashboard': 'Dashboard',
  'Page 1': 'Page 1',
  'Page 2': 'Page 2',
  'Profile': 'Profile',
  'Users': 'Users',
  'Contact Information': 'Contact Information',
  'Accounting Settings': 'Accounting Settings',
  'Team': 'Team',
  'Customize your company settings here.': 'Customize your company settings here.',
  'ServiceName': 'ServiceName',
  'Features': 'Features',
  'Pricing': 'Pricing',
  'Login': 'Login',
  'Get Started': 'Get Started',
  'Open menu': 'Open menu',
  'Light': 'Light',
  'Dark': 'Dark',
  'System': 'System',
  'Blog': 'Blog',
  'Enterprise': 'Enterprise',
  'Privacy Policy': 'Privacy Policy',
  'Terms of Service': 'Terms of Service',
  'Documentation': 'Documentation',
  'Tutorials': 'Tutorials',
  'Changelog': 'Changelog',
  'Sign up': 'Sign up',
  'All rights reserved': 'All rights reserved',
  'Something went wrong': 'Something went wrong',
  'Passwords do not match': 'Passwords do not match',
  'Password must be at least 6 characters long': 'Password must be at least 6 characters long',
  'An account with this email already exists': 'An account with this email already exists',
  'Failed to create account. Please try again.': 'Failed to create account. Please try again.',
  'Account created but failed to sign in. Please try logging in.': 'Account created but failed to sign in. Please try logging in.',
  'Network error. Please check your connection and try again.': 'Network error. Please check your connection and try again.',
  'Create your account': 'Create your account',
  'Sign up with your Google account or email and password': 'Sign up with your Google account or email and password',
  'Sign up with Google': 'Sign up with Google',
  'Or continue with': 'Or continue with',
  'Full Name': 'Full Name',
  'John Doe': 'John Doe',
  'Email': 'Email',
  'Password': 'Password',
  'Confirm Password': 'Confirm Password',
  'Creating account...': 'Creating account...',
  'Create Account': 'Create Account',
  'Already have an account?': 'Already have an account?',
  'Sign in': 'Sign in',
  'By clicking continue, you agree to our': 'By clicking continue, you agree to our',
  'and': 'and',
  'Failed to sign in with Google. Please try again.': 'Failed to sign in with Google. Please try again.',
  'An error occurred during sign in. Please try again.': 'An error occurred during sign in. Please try again.',
  'An unexpected error occurred. Please try again.': 'An unexpected error occurred. Please try again.',
  'Welcome back': 'Welcome back',
  'Login with your Google account or email and password': 'Login with your Google account or email and password',
  'Login with Google': 'Login with Google',
  'Forgot your password?': 'Forgot your password?',
  'Signing in...': 'Signing in...',
  'Don\'t have an account?': 'Don\'t have an account?',
  'Toggle theme': 'Toggle theme',
  'Select language': 'Select language',
  'Something went wrong, please contact support': 'Something went wrong, please contact support',
  'Please type \'delete\' to confirm': 'Please type \'delete\' to confirm',
  'You must decide what to do with all companies you own.': 'You must decide what to do with all companies you own.',
  'delete': 'delete',
  'Manage your account settings and logout options': 'Manage your account settings and logout options',
  'Session Management': 'Session Management',
  'Sign out from your account': 'Sign out from your account',
  'Loading...': 'Loading...',
  'Log out from all devices': 'Log out from all devices',
  'Permanently delete your account and all associated data.': 'Permanently delete your account and all associated data.',
  'This action cannot be undone.': 'This action cannot be undone.',
  'You are about to permanently delete your account.': 'You are about to permanently delete your account.',
  'cannot be undone': 'cannot be undone',
  'You own': 'You own',
  'Unnamed Company': 'Unnamed Company',
  'Unchecked companies will require you to transfer ownership first.': 'Unchecked companies will require you to transfer ownership first.',
  'Type': 'Type',
  'to confirm:': 'to confirm:',
  'Type \'delete\' here': 'Type \'delete\' here',
  'Cancel': 'Cancel',
  'Deleting...': 'Deleting...',
  'Failed to load team data': 'Failed to load team data',
  'Failed to invite user': 'Failed to invite user',
  'Failed to remove user': 'Failed to remove user',
  'Failed to transfer ownership': 'Failed to transfer ownership',
  'Failed to update role': 'Failed to update role',
  'Dismiss': 'Dismiss',
  'Team Members': 'Team Members',
  'Manage team members and their roles': 'Manage team members and their roles',
  'No team members found': 'No team members found',
  'Make Admin': 'Make Admin',
  'Make User': 'Make User',
  'Transfer Ownership': 'Transfer Ownership',
  'Remove': 'Remove',
  'Pending Invitations': 'Pending Invitations',
  'Users who have been invited but haven\'t accepted yet': 'Users who have been invited but haven\'t accepted yet',
  'Invited by': 'Invited by',
  'Invite New Member': 'Invite New Member',
  'Send an invitation to add someone to your team': 'Send an invitation to add someone to your team',
  'Email Address': 'Email Address',
  'Enter email address': 'Enter email address',
  'Role': 'Role',
  'Select Role': 'Select Role',
  'Admin': 'Admin',
  'User': 'User',
  'Sending...': 'Sending...',
  'Send Invitation': 'Send Invitation',
  'Remove Team Member': 'Remove Team Member',
  'Are you sure you want to remove': 'Are you sure you want to remove',
  'from this company?': 'from this company?',
  'Are you sure you want to transfer ownership to': 'Are you sure you want to transfer ownership to',
  'You will become an admin and lose owner privileges.': 'You will become an admin and lose owner privileges.',
  'Saving...': 'Saving...',
  'Save Changes': 'Save Changes',
  'Failed to save company data': 'Failed to save company data',
  'Basic Information': 'Basic Information',
  'Essential company details and registration information': 'Essential company details and registration information',
  'Company Name': 'Company Name',
  'Enter company name': 'Enter company name',
  'Organization Number': 'Organization Number',
  'Enter organization number': 'Enter organization number',
  'Company Type': 'Company Type',
  'Select Company Type': 'Select Company Type',
  'Limited Company': 'Limited Company',
  'General Partnership': 'General Partnership',
  'Limited Partnership': 'Limited Partnership',
  'Sole Proprietorship': 'Sole Proprietorship',
  'Housing Cooperative': 'Housing Cooperative',
  'Economic Association': 'Economic Association',
  'Failed to delete company': 'Failed to delete company',
  'Danger Zone': 'Danger Zone',
  'Irreversible and destructive actions for your company': 'Irreversible and destructive actions for your company',
  'Leave': 'Leave',
  'Company': 'Company',
  'Remove yourself from': 'Remove yourself from',
  'Loading team data...': 'Loading team data...',
  'Delete Company': 'Delete Company',
  'Permanently delete': 'Permanently delete',
  'This action cannot be undone and will remove data.': 'This action cannot be undone and will remove data.',
  'This will delete:': 'This will delete:',
  'All data associated with the company': 'All data associated with the company',
  'You are about to permanently delete': 'You are about to permanently delete',
  'This action': 'This action',
  'Address Information': 'Address Information',
  'Company physical address and location details': 'Company physical address and location details',
  'Address': 'Address',
  'Postal Code': 'Postal Code',
  'City': 'City',
  'Address Line 2': 'Address Line 2',
  'Apartment, suite, etc. (optional)': 'Apartment, suite, etc. (optional)',
  'Phone, email, and contact person details': 'Phone, email, and contact person details',
  'Phone': 'Phone',
  'Contact Person': 'Contact Person',
  'Failed to update company': 'Failed to update company',
  'VAT & Tax Settings': 'VAT & Tax Settings',
  'Configure VAT reporting and tax-related settings': 'Configure VAT reporting and tax-related settings',
  'VAT Reporting Period': 'VAT Reporting Period',
  'Select VAT Reporting Period': 'Select VAT Reporting Period',
  'Yearly': 'Yearly',
  'Quarterly': 'Quarterly',
  'Monthly': 'Monthly',
  'Accounting Method': 'Accounting Method',
  'Choose the accounting method for your company': 'Choose the accounting method for your company',
  'Select Accounting Method': 'Select Accounting Method',
  'Invoice Method': 'Invoice Method',
  'Cash Method': 'Cash Method',
  'Annual Report Status': 'Annual Report Status',
  'Information about your company\'s annual reporting status': 'Information about your company\'s annual reporting status',
  'Company has completed at least one annual report': 'Company has completed at least one annual report',
  'Check this if your company has already filed at least one annual report': 'Check this if your company has already filed at least one annual report',
  'Create a new company': 'Create a new company',
  'Create your first company': 'Create your first company',
  'Creating Company': 'Creating Company',
  'An error occurred while creating the company': 'An error occurred while creating the company',
  'VAT Registration Number': 'VAT Registration Number',
  'Contact Information (Optional)': 'Contact Information (Optional)',
  'Accounting Settings (Optional)': 'Accounting Settings (Optional)',
  'Fiscal Year Start': 'Fiscal Year Start',
  'Fiscal Year End': 'Fiscal Year End',
  'All Invitations Processed': 'All Invitations Processed',
  'You have responded to all pending invitations.': 'You have responded to all pending invitations.',
  'Continue to Dashboard': 'Continue to Dashboard',
  'Company Invitations': 'Company Invitations',
  'You have an invitation': 'You have an invitation',
  'Please review and respond to each invitation below.': 'Please review and respond to each invitation below.',
  'Accepting...': 'Accepting...',
  'Accept': 'Accept',
  'Decline': 'Decline',
  'Decline Invitation': 'Decline Invitation',
  'Are you sure you want to decline the invitation?': 'Are you sure you want to decline the invitation?',
  'This action cannot be undone, and you would need to be invited again to join this company.': 'This action cannot be undone, and you would need to be invited again to join this company.',
  'Invalid email or password. Please check your credentials and try again.': 'Invalid email or password. Please check your credentials and try again.',
  'How will a company car affact my salary and tax?': 'How will a company car affact my salary and tax?',
  'As the company owner, you cannot leave the company directly.': 'As the company owner, you cannot leave the company directly.',
  'To leave this company, you need to transfer ownership to another team member first.': 'To leave this company, you need to transfer ownership to another team member first.',
  'No team members will be able to access the company or recover it': 'No team members will be able to access the company or recover it',
  'The company and all its data will be permanently deleted': 'The company and all its data will be permanently deleted',
  'and will permanently remove all data associated with this company': 'and will permanently remove all data associated with this company',
  'Fill in the company information to get started with your accounting': 'Fill in the company information to get started with your accounting'} as const;

export default enTranslations;
